name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build-gcc:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        gcc-version: [6, 7, 8, 9, 10, 11, 12]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Build Binac
        run: |
          apt-get update && apt-get install -y -q nasm
          make
      - name: Test Binac
        run: |
          ./load.sh
