name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build-gcc:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        gcc-version: [
          "9-bullseye",
          "10-bullseye",
          "11-bullseye",
          "12-bullseye",
          "13-bookworm",
          "14-bookworm",
          "15-bookworm"
        ]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Print GCC information
        run: gcc --version
      - name: Build Binac
        run: |
          apt-get update && apt-get install -y -q nasm
          make
      - name: Test Binac
        run: |
          ./load.sh
