name: Main Workflow
on: [push]
jobs:
  build-gcc:
    name: Build
    strategy:
      matrix:
        gcc-version: [5, 6, 7, 8, 9]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - name: Checkout code from repository
      - uses: actions/checkout@v3
      - name: Build Binac
        run: |
          apt-get update && apt-get install -y -q nasm
          make
      - name: Test Binac
        run: |
          ./load.sh
